//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Restoran1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Блюда.
    /// </summary>
    // *** Start programmer edit section *** (Блюда CustomAttributes)

    // *** End programmer edit section *** (Блюда CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("БлюдаE", new string[] {
            "КодБлюда as \'Код блюда\'",
            "Наименование as \'Наименование\'",
            "Стоимотсь as \'Стоимотсь\'"})]
    [AssociatedDetailViewAttribute("БлюдаE", "СоставБлюда", "СоставБлюдаE", true, "", "Состав блюда", true, new string[] {
            ""})]
    [View("БлюдаL", new string[] {
            "КодБлюда as \'Код блюда\'",
            "Наименование as \'Наименование\'",
            "Стоимотсь as \'Стоимотсь\'"})]
    public class Блюда : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодБлюда;
        
        private string fНаименование;
        
        private double fСтоимотсь;
        
        private IIS.Restoran1.DetailArrayOfСоставБлюда fСоставБлюда;
        
        // *** Start programmer edit section *** (Блюда CustomMembers)

        // *** End programmer edit section *** (Блюда CustomMembers)

        
        /// <summary>
        /// КодБлюда.
        /// </summary>
        // *** Start programmer edit section *** (Блюда.КодБлюда CustomAttributes)

        // *** End programmer edit section *** (Блюда.КодБлюда CustomAttributes)
        public virtual int КодБлюда
        {
            get
            {
                // *** Start programmer edit section *** (Блюда.КодБлюда Get start)

                // *** End programmer edit section *** (Блюда.КодБлюда Get start)
                int result = this.fКодБлюда;
                // *** Start programmer edit section *** (Блюда.КодБлюда Get end)

                // *** End programmer edit section *** (Блюда.КодБлюда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Блюда.КодБлюда Set start)

                // *** End programmer edit section *** (Блюда.КодБлюда Set start)
                this.fКодБлюда = value;
                // *** Start programmer edit section *** (Блюда.КодБлюда Set end)

                // *** End programmer edit section *** (Блюда.КодБлюда Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Блюда.Наименование CustomAttributes)

        // *** End programmer edit section *** (Блюда.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Блюда.Наименование Get start)

                // *** End programmer edit section *** (Блюда.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Блюда.Наименование Get end)

                // *** End programmer edit section *** (Блюда.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Блюда.Наименование Set start)

                // *** End programmer edit section *** (Блюда.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Блюда.Наименование Set end)

                // *** End programmer edit section *** (Блюда.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Стоимотсь.
        /// </summary>
        // *** Start programmer edit section *** (Блюда.Стоимотсь CustomAttributes)

        // *** End programmer edit section *** (Блюда.Стоимотсь CustomAttributes)
        public virtual double Стоимотсь
        {
            get
            {
                // *** Start programmer edit section *** (Блюда.Стоимотсь Get start)

                // *** End programmer edit section *** (Блюда.Стоимотсь Get start)
                double result = this.fСтоимотсь;
                // *** Start programmer edit section *** (Блюда.Стоимотсь Get end)

                // *** End programmer edit section *** (Блюда.Стоимотсь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Блюда.Стоимотсь Set start)

                // *** End programmer edit section *** (Блюда.Стоимотсь Set start)
                this.fСтоимотсь = value;
                // *** Start programmer edit section *** (Блюда.Стоимотсь Set end)

                // *** End programmer edit section *** (Блюда.Стоимотсь Set end)
            }
        }
        
        /// <summary>
        /// Блюда.
        /// </summary>
        // *** Start programmer edit section *** (Блюда.СоставБлюда CustomAttributes)

        // *** End programmer edit section *** (Блюда.СоставБлюда CustomAttributes)
        public virtual IIS.Restoran1.DetailArrayOfСоставБлюда СоставБлюда
        {
            get
            {
                // *** Start programmer edit section *** (Блюда.СоставБлюда Get start)

                // *** End programmer edit section *** (Блюда.СоставБлюда Get start)
                if ((this.fСоставБлюда == null))
                {
                    this.fСоставБлюда = new IIS.Restoran1.DetailArrayOfСоставБлюда(this);
                }
                IIS.Restoran1.DetailArrayOfСоставБлюда result = this.fСоставБлюда;
                // *** Start programmer edit section *** (Блюда.СоставБлюда Get end)

                // *** End programmer edit section *** (Блюда.СоставБлюда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Блюда.СоставБлюда Set start)

                // *** End programmer edit section *** (Блюда.СоставБлюда Set start)
                this.fСоставБлюда = value;
                // *** Start programmer edit section *** (Блюда.СоставБлюда Set end)

                // *** End programmer edit section *** (Блюда.СоставБлюда Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "БлюдаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БлюдаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БлюдаE", typeof(IIS.Restoran1.Блюда));
                }
            }
            
            /// <summary>
            /// "БлюдаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View БлюдаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("БлюдаL", typeof(IIS.Restoran1.Блюда));
                }
            }
        }
    }
}
