//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Restoran1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ блюда.
    /// </summary>
    // *** Start programmer edit section *** (ЗаказБлюда CustomAttributes)

    // *** End programmer edit section *** (ЗаказБлюда CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ блюда")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказБлюдаE", new string[] {
            "Комментарий as \'Комментарий\'",
            "Блюда as \'Блюда\'",
            "Блюда.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Блюда.Наименование"})]
    [MasterViewDefineAttribute("ЗаказБлюдаE", "Блюда", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ЗаказБлюда : ICSSoft.STORMNET.DataObject
    {
        
        private string fКомментарий;
        
        private IIS.Restoran1.Блюда fБлюда;
        
        private IIS.Restoran1.Бронь fБронь;
        
        // *** Start programmer edit section *** (ЗаказБлюда CustomMembers)

        // *** End programmer edit section *** (ЗаказБлюда CustomMembers)

        
        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказБлюда.Комментарий CustomAttributes)

        // *** End programmer edit section *** (ЗаказБлюда.Комментарий CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарий
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказБлюда.Комментарий Get start)

                // *** End programmer edit section *** (ЗаказБлюда.Комментарий Get start)
                string result = this.fКомментарий;
                // *** Start programmer edit section *** (ЗаказБлюда.Комментарий Get end)

                // *** End programmer edit section *** (ЗаказБлюда.Комментарий Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказБлюда.Комментарий Set start)

                // *** End programmer edit section *** (ЗаказБлюда.Комментарий Set start)
                this.fКомментарий = value;
                // *** Start programmer edit section *** (ЗаказБлюда.Комментарий Set end)

                // *** End programmer edit section *** (ЗаказБлюда.Комментарий Set end)
            }
        }
        
        /// <summary>
        /// Заказ блюда.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказБлюда.Блюда CustomAttributes)

        // *** End programmer edit section *** (ЗаказБлюда.Блюда CustomAttributes)
        [PropertyStorage(new string[] {
                "Блюда"})]
        [NotNull()]
        public virtual IIS.Restoran1.Блюда Блюда
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказБлюда.Блюда Get start)

                // *** End programmer edit section *** (ЗаказБлюда.Блюда Get start)
                IIS.Restoran1.Блюда result = this.fБлюда;
                // *** Start programmer edit section *** (ЗаказБлюда.Блюда Get end)

                // *** End programmer edit section *** (ЗаказБлюда.Блюда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказБлюда.Блюда Set start)

                // *** End programmer edit section *** (ЗаказБлюда.Блюда Set start)
                this.fБлюда = value;
                // *** Start programmer edit section *** (ЗаказБлюда.Блюда Set end)

                // *** End programmer edit section *** (ЗаказБлюда.Блюда Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Restoran1.Бронь.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказБлюда.Бронь CustomAttributes)

        // *** End programmer edit section *** (ЗаказБлюда.Бронь CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Бронь"})]
        public virtual IIS.Restoran1.Бронь Бронь
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказБлюда.Бронь Get start)

                // *** End programmer edit section *** (ЗаказБлюда.Бронь Get start)
                IIS.Restoran1.Бронь result = this.fБронь;
                // *** Start programmer edit section *** (ЗаказБлюда.Бронь Get end)

                // *** End programmer edit section *** (ЗаказБлюда.Бронь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказБлюда.Бронь Set start)

                // *** End programmer edit section *** (ЗаказБлюда.Бронь Set start)
                this.fБронь = value;
                // *** Start programmer edit section *** (ЗаказБлюда.Бронь Set end)

                // *** End programmer edit section *** (ЗаказБлюда.Бронь Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказБлюдаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказБлюдаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказБлюдаE", typeof(IIS.Restoran1.ЗаказБлюда));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаказБлюда.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаказБлюда CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаказБлюда CustomAttributes)
    public class DetailArrayOfЗаказБлюда : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Restoran1.DetailArrayOfЗаказБлюда members)

        // *** End programmer edit section *** (IIS.Restoran1.DetailArrayOfЗаказБлюда members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаказБлюда by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаказБлюда.
        /// </summary>
        public DetailArrayOfЗаказБлюда(IIS.Restoran1.Бронь fБронь) : 
                base(typeof(ЗаказБлюда), ((ICSSoft.STORMNET.DataObject)(fБронь)))
        {
        }
        
        public IIS.Restoran1.ЗаказБлюда this[int index]
        {
            get
            {
                return ((IIS.Restoran1.ЗаказБлюда)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Restoran1.ЗаказБлюда dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
